[package]
name = "one-billion-row-challenge"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "baseline", "common", 
]

[[bin]]
name="baseline"
path="baseline/"

# [dependencies]

# [profile.release]
# debug = false
# opt-level = 3


